language: php
php:
    - '7.0'
before_script:
    - composer install
script:
    - mkdir -p build/logs
    - bin/phpunit -c phpunit.xml.dist Tests/Unit --coverage-clover build/logs/clover.xml
    - bin/phpunit -c phpunit.xml.dist Tests/Functional
after_success:
  - travis_retry php bin/coveralls